services:
  php-minimum:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/vendor
    environment:
      - PHP_INI_DIR=/usr/local/etc/php/conf.d
    expose:
      - 9000

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - php-minimum